site_title = "MyArxiv"
limit_days = 7
cache_url = "https://pommespeter.github.io/Arxiv-Pusher/cache.json"

[[sources]]
limit = 200
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 200
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 150
category = "cs.IR"
title = "Information Retrieval"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.MM"
title = "Multimedia"

[[sources]]
limit = 240
category = "cs.AI"
title = "Artificial Intelligent"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
